### ISSUE TITLE
Функция для получения цветов из Common

### ISSUE THREAD

**Issue by therteenten** [therteenten/sassify#12]
В папке *./common/colors/* есть большое количество карт (`Map`) цветов (Apple, Microsoft Windows, Material Design Colors), но чтобы их получить нужно прописать большую строчку кода. Например:

```scss
@use 'node_modules/@therteenten/sassify' as sassify with (
  // настройки Sassify
);

// ...

.text-error {
  color: sassify.map-deep-get(sassify.$color--md-red, 400);
  // ...
}
```

Слишком много кода, который можно упростить, написав функции, которые сами будут брать нужные цвета. Например:

```scss
// импорт Sassify показывать не буду, но он должен быть 

.text-error {
  color: sassify.color-md(red, 400);
  // или
  color: sassify.color-apple(ios-dark, red);
}
```

По мне выглядит опрятнее и достаточно понятнее. А если Sassify импортировано глобально (т.е. без пространства имён) через `*`, то ещё проще:

```scss
.text-error {

  color: color-md(red, 400);
  
  // или
  color: color-apple(macos, red);
  
  // ну и фон окрасим ради интереса 
  background-color: color-md(grey, 50);
  
}
```

Думаю вариант прям очень хороший. Надо реализовать это в грядущем обновлении Sassify.
