### ISSUE TITLE
Миксин AMCSS

### ISSUE THREAD

**Issue by therteenten** [therteenten/sassify#7]
Миксин `amcss` позволит писать CSS-стили по методологии [AMCSS](https://habr.com/ru/post/256109/):

```scss
// SCSS
@include amcss(module) {
	color: red;
}

@include amcss(module, blue) {
	color: blue;
}

@include amcss(module, large) {
	font-size: 2em;
}
```
```css
/* CSS */
[am-module] {
	color: red;
}

[am-module~="blue"] {
	color: blue;
}

[am-module~="large"] {
	font-size: 2em;
}
```
