### ISSUE TITLE
Миксины и функций для работы с кастомными свойствами CSS

### ISSUE THREAD

**Issue by therteenten** [therteenten/sassify#9]
Было бы неплохо накидать функций и миксинов, которые упростили бы работы с кастомными свойствами CSS.

К примеру:
- функция `var`, которая преобразует переменную в кастомное свойство и в качестве запаски кладет значение этой переменной:

  ```scss
  // SCSS
  .text-warn {
    color: sassify.var($color-orange);
  }
  ```
  ```css
  /* CSS */
  .text-warn {
    color: var(--color-orange, #FCBC05);
  }
  ```

- миксин `custom-props` будет из Sass-карты (map) создавать список кастомных свойств CSS:

```scss
  // SCSS
  @include sassify.custom-props(root, (
  color-white: #FFFFFF,
  color-orange: #FCBC05
  ));
  ```

  ```css
  /* CSS */
  :root {
    --color-white: #FFFFFF;
    --color-orange: #FCBC05;
  }
  ```
